### PR TITLE
Update make-layer.sh

### PR DESCRIPTION
**Pull request by akhilnegi**
Current url's are giving error due to the missing "n"

### CODE REVIEW

**Comment by JTunis** [comment]
Thanks @akhilnegi, it does look like PyTorch recently changed the download URLs with 1.6.0. From what I see, it looks like the diff is the concatenation of an "m" (not "n") if the Python version is not the most recent (<3.8).

For example the URL for torch 1.5.1, Python 3.8 is now: https://download.pytorch.org/whl/cpu/torch-1.5.1%2Bcpu-cp38-cp38-linux_x86_64.whl

and the URL for torch 1.5.1, Python 3.7 is: https://download.pytorch.org/whl/cpu/torch-1.5.1%2Bcpu-cp37-cp37m-linux_x86_64.whl

For reference, I'm getting the URLs from [here](https://download.pytorch.org/whl/cpu/torch_stable.html), so I'm curious where you saw "n" being appended to the Python version rather than "m"

**Comment by akhilnegi** [comment]
My bad, yes it was an 'm' for the older versions.

**Comment by JTunis** [comment]
@akhilnegi Turns out the "m" at the end of a Python version means it was implemented with the Pymalloc object allocator to speed up operations (credit: https://stackoverflow.com/questions/16675865/difference-between-python3-and-python3m-executables/16677339), and it looks like the "m" flag was removed starting with Python 3.8 due to some C API changes (https://docs.python.org/3/whatsnew/3.8.html#build-and-c-api-changes)

**Comment by JTunis** [comment]
@akhilnegi thanks for pointing this out -- I pushed a fix in #6 that can probably be generalized a little more in the future

**Pull request closed without merging**
